# CI
# Installs Dependencies, runs tests and builds the app
name: Push & Test Express App

on:
  push:
    branches: ["dev"]
  # pull_request:
  #   branches: ["main"]

jobs:
  builds:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install Dependencies
        run: npm install && rebuild sqlite3
      - name: Run Tests
        run: npm test
